<a href="https://colab.research.google.com/github/SanjeevKumar369/My_Pixeltest_June_2023/blob/main/03_06_2024_Pix_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
np.random.rand(4)

array([0.51832212, 0.45846562, 0.14474846, 0.57969269])

In [4]:
np.random.seed(42)

In [8]:
test=np.random.randint(90,98,3)
test


array([92, 92, 97])

In [9]:
type(test)

numpy.ndarray

In [10]:
test.shape

(3,)

In [12]:
test.max()

97

In [14]:
test.argmax()

2

In [15]:
num=test.argmax()
num

2

In [16]:
type(num)

numpy.int64

In [18]:
test

array([92, 92, 97])

In [19]:
num1=test.argmax()
num1

2

In [22]:
float_num=10.20

In [23]:
float_num

10.2

In [24]:
type(float_num)

float

In [30]:
labels=['A B C D E F G H I']

In [31]:
labels

['A B C D E F G H I']

In [37]:
type(labels)

list

In [41]:
# PANDA DATAFRAME
np.random.rand(5,3)
df=pd.DataFrame(np.random.rand(5,3))
df



0         1         2
0  0.395150  0.926659  0.727272
1  0.326541  0.570444  0.520834
2  0.961172  0.844534  0.747320
3  0.539692  0.586751  0.965255
4  0.607034  0.275999  0.296274

In [42]:
df=pd.DataFrame(np.random.rand(5,3))
df=Index=['A B C D E'],
columns=['c1, c2, c3']
df

(['A B C D E'],)

In [44]:
df.shape


AttributeError: 'tuple' object has no attribute 'shape'