<a href="https://colab.research.google.com/github/SanjeevKumar369/My_Pixeltest_June_2023/blob/main/Pix_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
num=np.arange(0,10,2)
print(num)


[0 2 4 6 8]


In [3]:
num1=np.linspace(0,10,2)
print(num1)

[ 0. 10.]


In [4]:
num2=np.linspace(0,10,5)
print(num2)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
num3=np.eye(7)
print(num3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [8]:
type(num3)

numpy.ndarray

In [9]:
np.random.rand(4)

array([0.2983218 , 0.39710627, 0.5434834 , 0.82336545])